### ISSUE TITLE
Issues encountered in reproduction of finetuning

### ISSUE THREAD

**Issue by RexGPT** [Yangyi-Chen/SOLO#11]
Hi @Yangyi-Chen ，Thank you for open-sourcing this excellent work! I encountered a few issues while reproducing the fine-tuning process:

1. It seems that the `hf_train.py` script in the repository is not your local version, as the `src.model` module is missing from [this line](https://github.com/Yangyi-Chen/SOLO/blob/main/src/scripts/hf_train.py#L6).
2. During model forward, this part of [code](https://github.com/Yangyi-Chen/SOLO/blob/main/scripts/model/modeling_solo.py#L268-L285) ignores the processing of cases, where `vision_patches=None`.
3. When running the script further, I encountered an issue that required adding `find_unused_parameters=True` to proceed.
4. After resolving the above, I successfully ran the script. However, it reported a `cuda out of memory` error after several iterations, even though I used an H20 GPU with 97GB memory, which is larger than the 80GB A100 mentioned in the paper.

![image](https://github.com/user-attachments/assets/8168146d-efe9-40a6-b77c-2147ef891e7b)

Would you be able to provide some insights or suggestions to resolve these issues?

Thanks in advance!

**Comment by RexGPT** [comment]
@Yangyi-Chen Even though I use provided [deepspeed config](https://github.com/Yangyi-Chen/SOLO/blob/main/config/accelerate/default_config.yaml), it still reports OOM with my H20 card

**Comment by Yangyi-Chen** [comment]
Hi! 
Many thanks for your interest. Are you using 1 single H20? Or 8XH20?

**Comment by RexGPT** [comment]
Thanks for your reply! I use 8xH20.

**Comment by Yangyi-Chen** [comment]
I see. The reason can be attributed to different GPU types. In my case, when I run the code on an 8XH100 server, the GPU memory is significantly increased. You may consider decreasing the sequence length.

**Comment by RexGPT** [comment]
Thanks for your prompt reply! I will give it a try.
