### ISSUE TITLE
[question] any plan to add multi images reasoning? or even multi frame reasoning for  video understanding

### ISSUE THREAD

**Issue by eisneim** [Yangyi-Chen/SOLO#3]
Hi authors of this great project!

Fuyu-8 is great for it's flexibility to accept any aspect ratio or resolution great for UI understanding, but we don't know how it's trained. but now we got SOLO!

just a quick question, the paper didn't mention anything about multi image reasoning, is there a plan to do instruction tuning on multi image dataset like: [Mantis](https://huggingface.co/datasets/TIGER-Lab/Mantis-Instruct)  

one image with ≈1024 context length might be expensive but we can scale the image down to 224x224 for high level semantics, so  one video frame would be just ≈49 context length, in combination with recent 1m context length tricks we can do long video understanding using SOLO;  adding something like [tokenpacker](https://github.com/circleradon/tokenpacker) in between  projection layer and embedding layer we might use 32 tokens to represent a frame of a video

**Comment by Yangyi-Chen** [comment]
Hi Eisneim,
Many thanks for your encouragement and for sharing these great papers! Yes doing multi-image understanding and even performing video understanding is one of our future plans. But now we are focusing on further improving the fundamental capability of SOLO. We will list multi-image and video understanding as our next step. Thanks!
