### ISSUE TITLE
When will the finetune guideline be published?

### ISSUE THREAD

**Issue by Hongyuan-Tao** [Yangyi-Chen/SOLO#4]
Hello! Thank you for your awesome work! I'd like to ask when will the finetune guideline of Solo be published. I hope to do further research based on solo.

**Comment by Yangyi-Chen** [comment]
Hi Hongyuan, 
Thanks for your interest! We have uploaded the code and guidance for instruction fine-tuning. 
However, we are still working on uploading all our data for instruction fine-tuning to the huggingface since it is too large (100+G). We will complete this soon.

**Comment by HYZ17** [comment]
Really looking forward to it.
