### ISSUE TITLE
Is the folder of [scripts/data/megatron_conversion] be deleted?

### ISSUE THREAD

**Issue by Hongyuan-Tao** [Yangyi-Chen/SOLO#6]
Dear authors！
         Thank you for your wonderful work!
         I'd like to pretrain your model but I found the folder [scripts/data/megatron_conversion] was deleted when I was trying to process the data.Is this folder be moved to another place?
        Looking forward to your early reply!

**Comment by xingyaoww** [comment]
Hey @Hongyuan-Tao, thanks for spotting this issue! The folder was indeed missing from the repo. 
I [just upload files](https://github.com/Yangyi-Chen/SOLO/commit/f7ed62b280eec204d89277b8db38d8722ef2a217) to the `scripts/data/megatron_conversion` folder - feel free to let us know (or re-open the issue) if you have further questions!
