### ISSUE TITLE
Training time details

### ISSUE THREAD

**Issue by Stephan-XUE** [Yangyi-Chen/SOLO#8]
Hello, thank you for your excellent work!
I noticed that you published the training steps of each stage in your paper, but would you also like to share the training time of each stage as well, or the steps per second information? For which we can have a better estimation of the total required computation resources.

**Comment by Yangyi-Chen** [comment]
Thanks for your interest. We do not keep track of the training time of each stage. However, the whole pre-training takes around 1 week on one 8XA100 80GB server.

**Comment by Stephan-XUE** [comment]
Thanks for your information!
